### ISSUE TITLE
Multiple index created: some are closed, some are open

### ISSUE THREAD

**Issue by ZaneCEO** [Smile-SA/smile-magento-elasticsearch#128]
hi guys,
I'm working on a Magento 1.9.2.1 installation with smile-magento-elasticsearch already installed and configured.

There are no fancy configuration, just step-by-step following of the guide.

Everything seems to be working but when i look at the HQ, i see multiple index:

![img](https://s2.postimg.org/u7pm4h1dl/indexes.png)

I would like to understand why there are multiple indexes and why some are open while some are closed. Is this a normal, expected behaviour?

I'm scratching my head about this because I've a cron script that runs this:

`shell/indexer.php -- -reindex catalogsearch_fulltext`

```
REINDEX_NIGHTLY START --> Thu Dec 14 04:00:01 CET 2017
Esecuzione catalogsearch_fulltext...
Catalog Search Index index process unknown error:
exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response
[status code] 400
[reason phrase] Bad Request
[url] http://167.114.235.124:9200/projectname-20171214-030002' in /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Exception/BadResponseException.php:43
Stack trace:
#0 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response))
#1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /redacted/public_html/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /redacted/public_html/lib/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event))
#4 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\Common\Event))
#5 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(378): Guzzle\Http\Message\Request->processResponse(Array)
#6 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Message/EntityEnclosingRequest.php(49): Guzzle\Http\Message\Request->setState('complete', Array)
#7 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(303): Guzzle\Http\Message\EntityEnclosingRequest->setState('complete', Array)
#8 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#9 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#10 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#11 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#12 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#13 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#14 /redacted/public_html/lib/vendor/guzzle/http/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#15 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(189): Guzzle\Http\Message\Request->send()
#16 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#17 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/projectname-201...', Array, '{"settings":{"n...')
#18 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/projectname-201...', Array, Array)
#19 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#20 /redacted/public_html/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(368): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#21 /redacted/public_html/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(449): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#22 /redacted/public_html/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#23 /redacted/public_html/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#24 /redacted/public_html/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#25 /redacted/public_html/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#26 /redacted/public_html/shell/indexer.php(216): Mage_Shell_Compiler->run()
#27 {main}

Next exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message '{"error":"IndexAlreadyExistsException[[projectname-20171214-030002] already exists]","status":400}' in /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php:266
Stack trace:
#0 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"settings":{"n...')
#1 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"settings":{"n...')
#2 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('POST', '/projectname-201...', Array, '{"settings":{"n...')
#3 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('POST', '/projectname-201...', Array, Array)
#4 /redacted/public_html/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(839): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /redacted/public_html/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(368): Elasticsearch\Namespaces\IndicesNamespace->create(Array)
#6 /redacted/public_html/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Index.php(449): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->_prepareIndex()
#7 /redacted/public_html/app/code/community/Smile/ElasticSearch/Model/Indexer/Fulltext.php(193): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Index->prepareNewIndex()
#8 /redacted/public_html/app/code/core/Mage/Index/Model/Process.php(212): Smile_ElasticSearch_Model_Indexer_Fulltext->reindexAll()
#9 /redacted/public_html/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()
#10 /redacted/public_html/shell/indexer.php(168): Mage_Index_Model_Process->reindexEverything()
#11 /redacted/public_html/shell/indexer.php(216): Mage_Shell_Compiler->run()
#12 {main}
````

Why `IndexAlreadyExistsException`? shouldn't the task just update the existing index?

Thanf for your support!

**Comment by strubloid** [comment]
any news about this issue?

**Comment by ZaneCEO** [comment]
Not on my side. I'm still experiencing this issue. @strubloid : do you see it too?
