### ISSUE TITLE
Failed to execute phase [query_fetch], all shards failed on MultiStore website at catalogsearch/result page

### ISSUE THREAD

**Issue by eugeneto** [Smile-SA/smile-magento-elasticsearch#136]
Hello support team.
We run Elastic Search 1.3.0 on Community Magento ver. 1.9.2.2.
We added new website. Totally 2 Websites: each website has a unique ID at Site Configuration tab matching their ID in magento. We faced following issue when searching:
https://sitename.com/catalogsearch/result/?q=test
Reindex and Clear Cache doesn't help.

Could you please help me to resolve this issue?

**Error Report:**
a:5:{i:0;s:1752:"{"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[RSpz0zu-SvineMlmLU5Hng][daliliama-20180329-164904][0]: SearchParseException[[daliliama-20180329-164904][0]: query[filtered(+(+(MatchNoDocsQuery | category_name_he.whitespace:test~1 | sku:test~1^10.0 | search_he.whitespace:test~1)))->cache(BooleanFilter(+cache(visibility:`\b\u0000\u0000\u0000\u0003 visibility:`\b\u0000\u0000\u0000\u0004) +cache(status:[1 TO 1]) +cache(in_stock:T) +cache(QueryWrapperFilter(categories:[2 TO 2] show_in_categories:[2 TO 2])) +cache(store_id:[2 TO 2])))],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must\":[{\"multi_match\":{\"query\":\"test\",\"type\":\"best_fields\",\"minimum_should_match\":\"100%\",\"fields\":[\"search_he.whitespace\",\"sku^10\",\"category_name_he.whitespace^1\",\"search_he.shingle\"],\"fuzziness\":\"0.75\",\"prefix_length\":\"1\",\"max_expansions\":\"10\",\"cutoff_frequency\":0.15}}]}}]}},\"filter\":{\"bool\":{\"must\":[{\"terms\":{\"visibility\":[3,4]}},{\"terms\":{\"status\":[1]}},{\"terms\":{\"in_stock\":[1]}},{\"fquery\":{\"query\":{\"query_string\":{\"query\":\"(categories:2 OR show_in_categories:2)\"}},\"_cache\":true}},{\"terms\":{\"store_id\":[2]}}],\"_cache\":true}}}},\"facets\":{\"categories\":{\"terms\":{\"size\":10,\"order\":\"count\",\"script_field\":\"doc.categories.values + doc.show_in_categories.values\"}}},\"fields\":[\"entity_id\"],\"track_scores\":true,\"sort\":[{\"_score\":{\"order\":\"desc\",\"missing\":9223372036854775806,\"ignore_unmapped\":true}}],\"from\":0,\"size\":2400}]]]; nested: ScriptException[dynamic scripting for [groovy] disabled]; }]","status":400}";i:1;s:5692:"#0 /var/www/html/.modman/smile-magento-elasticsearch/src/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"query":{"filt...')
#1 /var/www/html/.modman/smile-magento-elasticsearch/src/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"filt...')
#2 /var/www/html/.modman/smile-magento-elasticsearch/src/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/daliliama/prod...', Array, '{"query":{"filt...')
#3 /var/www/html/.modman/smile-magento-elasticsearch/src/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/daliliama/prod...', Array, Array)
#4 /var/www/html/.modman/smile-magento-elasticsearch/src/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1010): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /var/www/html/.modman/smile-magento-elasticsearch/src/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Query/Abstract.php(219): Elasticsearch\Client->search(Array)
#6 /var/www/html/.modman/smile-magento-elasticsearch/src/app/code/community/Smile/ElasticSearch/Model/Resource/Catalog/Product/Collection.php(227): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Query_Abstract->search()
#7 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(864): Smile_ElasticSearch_Model_Resource_Catalog_Product_Collection->_beforeLoad()
#8 /var/www/html/app/code/core/Mage/Review/Model/Observer.php(78): Mage_Eav_Model_Entity_Collection_Abstract->load()
#9 /var/www/html/app/code/core/Mage/Core/Model/App.php(1358): Mage_Review_Model_Observer->catalogBlockProductCollectionBeforeToHtml(Object(Varien_Event_Observer))
#10 /var/www/html/app/code/core/Mage/Core/Model/App.php(1331): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Review_Model_Observer), 'catalogBlockPro...', Object(Varien_Event_Observer))
#11 /var/www/html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_block_p...', Array)
#12 /var/www/html/app/code/core/Mage/Catalog/Block/Product/List.php(164): Mage::dispatchEvent('catalog_block_p...', Array)
#13 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Catalog_Block_Product_List->_beforeToHtml()
#14 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#15 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('search_result_l...', true)
#16 /var/www/html/app/code/core/Mage/CatalogSearch/Block/Result.php(161): Mage_Core_Block_Abstract->getChildHtml('search_result_l...')
#17 /var/www/html/app/design/frontend/customtheme/default/template/catalogsearch/result.phtml(42): Mage_CatalogSearch_Block_Result->getProductListHtml()
#18 /var/www/html/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/a...')
#19 /var/www/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/custom...')
#20 /var/www/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#21 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#22 /var/www/html/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#23 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#24 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#25 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#26 /var/www/html/app/design/frontend/blueprint/default/template/page/1column.phtml(46): Mage_Core_Block_Abstract->getChildHtml('content')
#27 /var/www/html/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/a...')
#28 /var/www/html/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/bluepr...')
#29 /var/www/html/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#30 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#31 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#32 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#33 /var/www/html/app/code/core/Mage/CatalogSearch/controllers/ResultController.php(80): Mage_Core_Controller_Varien_Action->renderLayout()
#34 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_CatalogSearch_ResultController->indexAction()
#35 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#36 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#37 /var/www/html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#38 /var/www/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#39 /var/www/html/index.php(83): Mage::run('', 'store')
#40 {main}";s:3:"url";s:29:"/catalogsearch/result/?q=test";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:2:"he";}

**Comment by ThomasCouet** [comment]
Hello, 

To fix this issue with Magento 1.9.x, I added the following line into /etc/elasticsearch/elasticsearch.yml `script.disable_dynamic: false`
Then, please restart the service. 

Regards.
