### ISSUE TITLE
Too Many Clauses: maxClaseCount is set to 10240

### ISSUE THREAD

**Issue by kinexm** [Smile-SA/smile-magento-elasticsearch#147]
Getting this Error in Logs:

18-10-19 12:03:50] report.WARNING: Request Failure: {"method":"GET","uri":"http://localhost:9200/badboy_m2_produc_default_catalog_product/product/_search","headers":{"Host":["localhost:9200"],"Content-Type":["application/json"],"Accept":["application/json"]},"HTTP code":500,"duration":3.460305,"error":"{\"error\":{\"root_cause\":[{\"type\":\"too_many_clauses\",\"reason\":\"too_many_clauses: maxClauseCount is set to 10240\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query_fetch\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"badboy_m2_produc_default_catalog_product_20181019_094817\",\"node\":\"b127n3jWR4i8SP5AEvMJsw\",\"reason\":{\"type\":\"too_many_clauses\",\"reason\":\"too_many_clauses: maxClauseCount is set to 10240\"}}],\"caused_by\":{\"type\":\"too_many_clauses\",\"reason\":\"too_many_clauses: maxClauseCount is set to 10240\"}},\"status\":500}"} []
[2018-10-19 12:03:50] report.WARNING: Response ["{\"error\":{\"root_cause\":[{\"type\":\"too_many_clauses\",\"reason\":\"too_many_clauses: maxClauseCount is set to 10240\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query_fetch\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"badboy_m2_produc_default_catalog_product_20181019_094817\",\"node\":\"b127n3jWR4i8SP5AEvMJsw\",\"reason\":{\"type\":\"too_many_clauses\",\"reason\":\"too_many_clauses: maxClauseCount is set to 10240\"}}],\"caused_by\":{\"type\":\"too_many_clauses\",\"reason\":\"too_many_clauses: maxClauseCount is set to 10240\"}},\"status\":500}"] []
[2018-10-19 12:03:50] report.ERROR: {"error":{"root_cause":[{"type":"too_many_clauses","reason":"too_many_clauses: maxClauseCount is set to 10240"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"badboy_m2_produc_default_catalog_product_20181019_094817","node":"b127n3jWR4i8SP5AEvMJsw","reason":{"type":"too_many_clauses","reason":"too_many_clauses: maxClauseCount is set to 10240"}}],"caused_by":{"type":"too_many_clauses","reason":"too_many_clauses: maxClauseCount is set to 10240"}},"status":500} [] []
[2018-10-19 12:03:54] report.ERROR: [500 Server Exception] too_many_clauses: too_many_clauses: maxClauseCount is set to 10240 [] []
[2018-10-19 12:03:54] report.ERROR: #0 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(680): Elasticsearch\Connections\Connection->tryDeserializeError(Array, 'Elasticsearch\\C...')
#1 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(639): Elasticsearch\Connections\Connection->tryDeserialize500Error(Array)
#2 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(276): Elasticsearch\Connections\Connection->process5xxError(Array, Array, Array)
#3 /app/ui4hvuskmmbca/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#4 /app/ui4hvuskmmbca/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#5 /app/ui4hvuskmmbca/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#6 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(294): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#7 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(171): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)
#8 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\Connections\Connection->performRequest('GET', '/badboy_m2_prod...', Array, '{"size":48,"sor...', Array, Object(Elasticsearch\Transport))
#9 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1578): Elasticsearch\Transport->performRequest('GET', '/badboy_m2_prod...', Array, Array, Array)
#10 /app/ui4hvuskmmbca/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(952): Elasticsearch\Client->performRequest(Object(Elasticsearch\Endpoints\Search))
#11 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/Client.php(155): Elasticsearch\Client->search(Array)
#12 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Adapter.php(108): Smile\ElasticsuiteCore\Client\Client->search(Array)
#13 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Adapter.php(82): Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Adapter->doSearch(Object(Smile\ElasticsuiteCore\Search\Request))
#14 /app/ui4hvuskmmbca/vendor/magento/module-search/Model/SearchEngine.php(42): Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Adapter->query(Object(Smile\ElasticsuiteCore\Search\Request))
#15 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(437): Magento\Search\Model\SearchEngine->search(Object(Smile\ElasticsuiteCore\Search\Request))
#16 /app/ui4hvuskmmbca/vendor/magento/framework/Data/Collection/AbstractDb.php(340): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFiltersBefore()
#17 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(472): Magento\Framework\Data\Collection\AbstractDb->_renderFilters()
#18 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(301): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFilters()
#19 /app/ui4hvuskmmbca/generated/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(128): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->getFacetedData('categories')
#20 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(134): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->getFacetedData('categories')
#21 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(181): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->_getItemsData()
#22 /app/ui4hvuskmmbca/vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php(159): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->_initItems()
#23 /app/ui4hvuskmmbca/vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php(148): Magento\Catalog\Model\Layer\Filter\AbstractFilter->getItems()
#24 /app/ui4hvuskmmbca/vendor/magento/module-catalog/Model/Layer/Category/AvailabilityFlag.php(33): Magento\Catalog\Model\Layer\Filter\AbstractFilter->getItemsCount()
#25 /app/ui4hvuskmmbca/vendor/magento/module-catalog/Model/Layer/Category/AvailabilityFlag.php(23): Magento\Catalog\Model\Layer\Category\AvailabilityFlag->canShowOptions(Array)
#26 /app/ui4hvuskmmbca/vendor/magento/module-layered-navigation/Block/Navigation.php(111): Magento\Catalog\Model\Layer\Category\AvailabilityFlag->isEnabled(Object(Magento\Catalog\Model\Layer\Search\Interceptor), Array)
#27 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php(91): Magento\LayeredNavigation\Block\Navigation->canShowBlock()
#28 /app/ui4hvuskmmbca/var/view_preprocessed/pub/static/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/templates/layer/view.phtml(1): Smile\ElasticsuiteCatalog\Block\Navigation->canShowBlock()
#29 /app/ui4hvuskmmbca/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/app/ui4hvuskmm...')
#30 /app/ui4hvuskmmbca/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Smile\ElasticsuiteCatalog\Block\Navigation), '/app/ui4hvuskmm...', Array)
#31 /app/ui4hvuskmmbca/vendor/magento/framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/app/ui4hvuskmm...')
#32 /app/ui4hvuskmmbca/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#33 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#34 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('catalogsearch.l...')
#35 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('catalogsearch.l...')
#36 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('catalogsearch.l...')
#37 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('catalogsearch.l...', false)
#38 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('catalogsearch.l...', false)
#39 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('sidebar.main', false)
#40 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sidebar.main')
#41 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sidebar.main')
#42 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sidebar.main', false)
#43 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('sidebar.main', false)
#44 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('div.sidebar.mai...', false)
#45 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('div.sidebar.mai...')
#46 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('div.sidebar.mai...')
#47 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('div.sidebar.mai...', false)
#48 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('div.sidebar.mai...', false)
#49 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns', false)
#50 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#51 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#52 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', false)
#53 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('columns', false)
#54 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#55 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#56 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#57 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', false)
#58 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false)
#59 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#60 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#61 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#62 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#63 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(586): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#64 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root', false)
#65 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#66 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#67 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#68 /app/ui4hvuskmmbca/vendor/magento/framework/View/Layout.php(955): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#69 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#70 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#71 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#72 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#73 /app/ui4hvuskmmbca/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#74 /app/ui4hvuskmmbca/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#75 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#76 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#77 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#78 /app/ui4hvuskmmbca/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#79 /app/ui4hvuskmmbca/vendor/magento/framework/App/View.php(221): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#80 /app/ui4hvuskmmbca/vendor/magento/module-catalog-search/Controller/Result/Index.php(149): Magento\Framework\App\View->renderLayout()
#81 /app/ui4hvuskmmbca/vendor/magento/module-catalog-search/Controller/Result/Index.php(93): Magento\CatalogSearch\Controller\Result\Index->getNotCacheableResult(Object(Magento\CatalogSearch\Helper\Data), Object(Magento\Search\Model\Query\Interceptor))
#82 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(58): Magento\CatalogSearch\Controller\Result\Index->execute()
#83 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('execute', Array)
#84 /app/ui4hvuskmmbca/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/CatalogSearch/ResultPlugin.php(98): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}()
#85 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(135): Smile\ElasticsuiteCatalog\Plugin\CatalogSearch\ResultPlugin->aroundExecute(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure))
#86 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}()
#87 /app/ui4hvuskmmbca/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(26): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('execute', Array, NULL)
#88 /app/ui4hvuskmmbca/vendor/magento/framework/App/Action/Action.php(107): Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute()
#89 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#90 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(138): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent('dispatch', Array)
#91 /app/ui4hvuskmmbca/vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php(81): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#92 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\CatalogSearch\Controller\Result\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#93 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(153): Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#94 /app/ui4hvuskmmbca/generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php(39): Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#95 /app/ui4hvuskmmbca/vendor/magento/framework/App/FrontController.php(55): Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#96 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#97 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#98 /app/ui4hvuskmmbca/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#99 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#100 /app/ui4hvuskmmbca/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#101 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#102 /app/ui4hvuskmmbca/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#103 /app/ui4hvuskmmbca/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#104 /app/ui4hvuskmmbca/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#105 /app/ui4hvuskmmbca/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#106 /app/ui4hvuskmmbca/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#107 /app/ui4hvuskmmbca/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#108 {main} [] []

**Comment by ksaho2** [comment]
Make sure it is actually set. I was running Docker and thought I had set it under the Java options, but it was wrong and it only took effect after I put it under:

```
environment:
      - indices.query.bool.max_clause_count=4096
```

Then the error went away.
