### ISSUE TITLE
SearchPhaseExecutionException[Failed to execute phase [query_fetch]

### ISSUE THREAD

**Issue by matrixbegins** [Smile-SA/smile-magento-elasticsearch#41]
HI All,
I am running module version `1.1.2`. And I am getting following error again and again.
```
a:5:{i:0;s:3737:"{"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[4vES2ScfRAOGJLXT2UbZNA][elasticsearch-20151125-110047][0]: SearchParseException[[elasticsearch-20151125-110047][0]: query[filtered(+ConstantScore(*:*))->cache(BooleanFilter(+cache(visibility:`\b\u0000\u0000\u0000\u0002 visibility:`\b\u0000\u0000\u0000\u0004) +cache(status:`\b\u0000\u0000\u0000\u0001) +cache(QueryWrapperFilter(ConstantScore(categories: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\r) ConstantScore(categories: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\b) ConstantScore(categories: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\f) (ConstantScore(categories: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000E) ConstantScore(categories: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000F) ConstantScore(categories: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000G)))) +cache(store_id:`\b\u0000\u0000\u0000\u0001)))],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"bool\":{\"must\":[{\"match_all\":[]}]}},\"filter\":{\"bool\":{\"must\":[{\"terms\":{\"visibility\":[\"2\",\"4\"]}},{\"terms\":{\"status\":[\"1\"]}},{\"fquery\":{\"query\":{\"query_string\":{\"query\":\"categories:13 OR (categories:8) OR (categories:12) OR (categories:69 OR (categories:70) OR (categories:71))\"}},\"_cache\":true}},{\"terms\":{\"store_id\":[\"1\"]}}],\"_cache\":true}}}},\"facets\":{\"categories_8\":{\"query\":{\"query_string\":{\"query\":\"(categories:8)\"}},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"categories_12\":{\"query\":{\"query_string\":{\"query\":\"(categories:12)\"}},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"categories_69\":{\"query\":{\"query_string\":{\"query\":\"(categories:69 OR (categories:70) OR (categories:71))\"}},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"lux_ring_size\":{\"terms\":{\"size\":250,\"order\":\"term\",\"field\":\"options_lux_ring_size_en.untouched\"},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"manufacturer\":{\"terms\":{\"size\":250,\"order\":\"term\",\"field\":\"options_manufacturer_en.untouched\"},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"metal_type\":{\"terms\":{\"size\":250,\"order\":\"term\",\"field\":\"options_metal_type_en.untouched\"},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"gender\":{\"terms\":{\"size\":250,\"order\":\"term\",\"field\":\"options_gender_en.untouched\"},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"condition\":{\"terms\":{\"size\":250,\"order\":\"term\",\"field\":\"options_condition_en.untouched\"},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"color\":{\"terms\":{\"size\":250,\"order\":\"term\",\"field\":\"color\"}},\"movement\":{\"terms\":{\"size\":250,\"order\":\"term\",\"field\":\"options_movement_en.untouched\"},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}},\"price_0_1\":{\"histogram\":{\"interval\":1,\"field\":\"price_0_1\"},\"facet_filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}}}},\"filter\":{\"bool\":{\"must\":[{\"terms\":{\"color\":[\"330,437,459\"]}}]}},\"fields\":[\"entity_id\"],\"track_scores\":true,\"sort\":[{\"_score\":\"desc\"},{\"id\":{\"order\":\"desc\",\"missing\":\"_last\",\"ignore_unmapped\":true}}],\"from\":0,\"size\":10000}]]]; nested: NumberFormatException[For input string: \"330,437,459\"]; }]","status":400}";i:1;s:4613:"#0 /var/www/live-app/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"query":{"filt...')
#1 /var/www/live-app/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"filt...')
#2 /var/www/live-app/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/elasticsearch/...', Array, '{"query":{"filt...')
#3 /var/www/live-app/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/elasticsearch/...', Array, Array)
#4 /var/www/live-app/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1010): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /var/www/live-app/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Query/Abstract.php(185): Elasticsearch\Client->search(Array)
#6 /var/www/live-app/app/code/community/Smile/ElasticSearch/Model/Resource/Catalog/Product/Collection.php(150): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Query_Abstract->search()
#7 /var/www/live-app/app/code/community/Smile/ElasticSearch/Model/Resource/Catalog/Product/Collection.php(83): Smile_ElasticSearch_Model_Resource_Catalog_Product_Collection->_beforeLoad()

#8 /var/www/live-app/app/code/community/Smile/ElasticSearch/Block/Catalog/Layer/View.php(200): Smile_ElasticSearch_Model_Resource_Catalog_Product_Collection->getSize()
#9 /var/www/live-app/app/design/frontend/truefacet/truefacet/template/catalog/layer/view.phtml(7): Smile_ElasticSearch_Block_Catalog_Layer_View->canShowBlock()
#10 /var/www/live-app/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/truefa...')
#11 /var/www/live-app/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/truefa...')
#12 /var/www/live-app/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#13 /var/www/live-app/app/code/core/Mage/Core/Block/Abstract.php(886): Mage_Core_Block_Template->_toHtml()
#14 /var/www/live-app/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#15 /var/www/live-app/app/code/core/Mage/Core/Block/Abstract.php(886): Mage_Core_Block_Text_List->_toHtml()
#16 /var/www/live-app/app/code/core/Mage/Core/Block/Abstract.php(605): Mage_Core_Block_Abstract->toHtml()
#17 /var/www/live-app/app/code/core/Mage/Core/Block/Abstract.php(549): Mage_Core_Block_Abstract->_getChildHtml('left', true)
#18 /var/www/live-app/app/design/frontend/truefacet/truefacet/template/page/1column-category.phtml(39): Mage_Core_Block_Abstract->getChildHtml('left')
#19 /var/www/live-app/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/truefa...')
#20 /var/www/live-app/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/truefa...')
#21 /var/www/live-app/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#22 /var/www/live-app/app/code/core/Mage/Core/Block/Abstract.php(886): Mage_Core_Block_Template->_toHtml()
#23 /var/www/live-app/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#24 /var/www/live-app/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#25 /var/www/live-app/app/code/core/Mage/Catalog/controllers/CategoryController.php(161): Mage_Core_Controller_Varien_Action->renderLayout()
#26 /var/www/live-app/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Catalog_CategoryController->viewAction()
#27 /var/www/live-app/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('view')
#28 /var/www/live-app/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#29 /var/www/live-app/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#30 /var/www/live-app/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#31 /var/www/live-app/index.php(87): Mage::run('default', 'store')
#32 {main}";s:3:"url";s:39:"/watches.html?color=330%2C437%2C459&p=2";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

```
As I am very new to elastic search not sure how to fix it. Any help is much appreciated.

**Comment by Ouzned** [comment]
Hi, 

It looks like your 'color' attribute is indexed as a number and you are trying to query this field with the value "330,437,459" which gives you a NumberFormatException

**Comment by afoucret** [comment]
This one should have been fixed since release 1.3.
Can you confirm.

**Comment by matrixbegins** [comment]
This problem I believe, we encountered when we were trying to implement multiple color selection. So we had to do some changes in extension to fix this issue. So from my side we can close this issue

**Comment by pixiemediaweb** [comment]
We're seeing the same error with the latest version downloaded today.  Magento EE 1.14.2, it occurs when trying to create virtual categories.   Any update on this?
