### ISSUE TITLE
Failed to execute phase [query_fetch]

### ISSUE THREAD

**Issue by sebfie** [Smile-SA/smile-magento-elasticsearch#58]
Hello, I tried to install your extension and I have this error : 

```
`a:5:{i:0;s:2070:"{"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[C-sqbOa8SaSfIKb9cZ4NQg][dastled-20160310-155606][0]: SearchParseException[[dastled-20160310-155606][0]: query[filtered(+ConstantScore(*:*))->cache(BooleanFilter(+cache(visibility:`\b\u0000\u0000\u0000\u0002 visibility:`\b\u0000\u0000\u0000\u0004) +cache(status:`\b\u0000\u0000\u0000\u0001) +cache(in_stock:T) +cache(QueryWrapperFilter(categories:[16 TO 16] show_in_categories:[16 TO 16])) +cache(store_id:`\b\u0000\u0000\u0000\u0001)))],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"bool\":{\"must\":[{\"match_all\":[]}]}},\"filter\":{\"bool\":{\"must\":[{\"terms\":{\"visibility\":[2,4]}},{\"terms\":{\"status\":[1]}},{\"terms\":{\"in_stock\":[1]}},{\"fquery\":{\"query\":{\"query_string\":{\"query\":\"(categories:16) OR (show_in_categories:16)\"}},\"_cache\":true}},{\"terms\":{\"store_id\":[1]}}],\"_cache\":true}}}},\"facets\":{\"categories_17\":{\"query\":{\"query_string\":{\"query\":\"((categories:17) OR (show_in_categories:17))\"}}},\"categories_18\":{\"query\":{\"query_string\":{\"query\":\"((categories:18) OR (show_in_categories:18))\"}}},\"categories_19\":{\"query\":{\"query_string\":{\"query\":\"((categories:19) OR (show_in_categories:19))\"}}},\"price_1_1\":{\"histogram\":{\"interval\":1,\"field\":\"price_1_1\"}},\"rating_filter\":{\"histogram\":{\"interval\":20,\"field\":\"rating_filter\"}},\"options_power_fr.untouched\":{\"histogram\":{\"interval\":1,\"field\":\"options_power_fr.untouched\"}}},\"fields\":[\"entity_id\"],\"track_scores\":true,\"sort\":[{\"position\":{\"order\":\"asc\",\"missing\":9223372036854775806,\"ignore_unmapped\":true,\"nested_path\":\"category_position\",\"nested_filter\":{\"term\":{\"category_id\":\"16\"}}}},{\"_score\":\"desc\"}],\"from\":0,\"size\":10}]]]; nested: ClassCastException[org.elasticsearch.index.fielddata.plain.SortedSetDVBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]; }]","status":400}";i:1;s:7557:"#0 /Users/sebfie/Documents/ProjetsWeb/dastled/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(194): Elasticsearch\Connections\GuzzleConnection->process4xxError(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Exception\ClientErrorResponseException), '{"query":{"filt...')
#1 /Users/sebfie/Documents/ProjetsWeb/dastled/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"filt...')
#2 /Users/sebfie/Documents/ProjetsWeb/dastled/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(166): Elasticsearch\Connections\GuzzleConnection->performRequest('GET', '/dastled/produc...', Array, '{"query":{"filt...')
#3 /Users/sebfie/Documents/ProjetsWeb/dastled/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(86): Elasticsearch\Transport->performRequest('GET', '/dastled/produc...', Array, Array)
#4 /Users/sebfie/Documents/ProjetsWeb/dastled/lib/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1010): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#5 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/community/Smile/ElasticSearch/Model/Resource/Engine/Elasticsearch/Query/Abstract.php(219): Elasticsearch\Client->search(Array)
#6 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/community/Smile/ElasticSearch/Model/Resource/Catalog/Product/Collection.php(227): Smile_ElasticSearch_Model_Resource_Engine_Elasticsearch_Query_Abstract->search()
#7 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(864): Smile_ElasticSearch_Model_Resource_Catalog_Product_Collection->_beforeLoad()
#8 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Review/Model/Observer.php(78): Mage_Eav_Model_Entity_Collection_Abstract->load()
#9 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Model/App.php(1358): Mage_Review_Model_Observer->catalogBlockProductCollectionBeforeToHtml(Object(Varien_Event_Observer))
#10 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Model/App.php(1331): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Review_Model_Observer), 'catalogBlockPro...', Object(Varien_Event_Observer))
#11 /Users/sebfie/Documents/ProjetsWeb/dastled/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_block_p...', Array)
#12 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Catalog/Block/Product/List.php(164): Mage::dispatchEvent('catalog_block_p...', Array)
#13 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Catalog_Block_Product_List->_beforeToHtml()
#14 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/local/Sns/Megamenu/Block/List.php(128): Mage_Core_Block_Abstract->toHtml()
#15 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/local/Sns/Megamenu/Block/List.php(168): Sns_Megamenu_Block_List->getItemHtml(Object(Varien_Object))
#16 /Users/sebfie/Documents/ProjetsWeb/dastled/app/design/frontend/default/dastled/template/sns/megamenu/megamenu.phtml(76): Sns_Megamenu_Block_List->getItemHtml(Object(Varien_Object), true)
#17 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(241): include('/Users/sebfie/D...')
#18 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#19 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#20 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/local/Sns/Megamenu/Block/List.php(72): Mage_Core_Block_Template->_toHtml()
#21 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(919): Sns_Megamenu_Block_List->_toHtml()
#22 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#23 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#24 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#25 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('megaMenu', true)
#26 /Users/sebfie/Documents/ProjetsWeb/dastled/app/design/frontend/default/dastled/template/page/html/header.phtml(151): Mage_Core_Block_Abstract->getChildHtml('megaMenu')
#27 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(241): include('/Users/sebfie/D...')
#28 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#29 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#30 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#31 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#32 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('header', true)
#33 /Users/sebfie/Documents/ProjetsWeb/dastled/app/design/frontend/default/dastled/template/page/2columns-left.phtml(41): Mage_Core_Block_Abstract->getChildHtml('header')
#34 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(241): include('/Users/sebfie/D...')
#35 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/defaul...')
#36 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#37 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#38 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#39 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#40 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/local/Sns/Ajaxfilter/controllers/Catalog/CategoryController.php(112): Mage_Core_Controller_Varien_Action->renderLayout()
#41 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Sns_Ajaxfilter_Catalog_CategoryController->viewAction()
#42 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#43 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#44 /Users/sebfie/Documents/ProjetsWeb/dastled/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#45 /Users/sebfie/Documents/ProjetsWeb/dastled/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#46 /Users/sebfie/Documents/ProjetsWeb/dastled/index.php(83): Mage::run('', 'store')
#47 {main}";s:3:"url";s:13:"/panneau.html";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:13:"public_french";}`
```

Any idea?

I have ES 1.3.2

**Comment by afoucret** [comment]
Hi,

I am sure the bug is related to the usage of the Sns Megamenu extension which can not work with our module (and will never).

You have to make a choice between this two extension of fix by yourself the incompatibilities.

BR,

**Comment by sebfie** [comment]
Oh, you think so? Trying disabling this extension

**Comment by afoucret** [comment]
To be more precise, the module you may experience out of the box on existing projects if there is modifications into the following areas :

* layer block and filters

* toolbar (moving it can be a problem just like with the SolR implementation of Magento)

* product listing

From what I see in the stacktrace (I have no access to the code since the modules are proprietary), the two extensions Sns_Ajaxfilter and Sns_Megamenu does such modifications.

**Comment by sebfie** [comment]
Ok, I used an other module, I close this issue
