### ISSUE TITLE
Failed to find mapping for name_fr.untouched

### ISSUE THREAD

**Issue by faissal-topo** [Smile-SA/smile-magento-elasticsearch#84]
Hello everyone
I have a problem :
When I use the autocompletion of focntion magento, nothing is displayed.
When I checked the ElasticSearch' log, I found the following error:
`-------------------------------------------------------------------------------------

[2016-10-06 10:30:15,577][DEBUG][action.search.type       ] [Chaka] All shards failed for phase: [query_fetch]
org.elasticsearch.search.SearchParseException: [fly-20161006-082831][0]: query[filtered(+function score (+autocomplete_fr.edge_ngram_front:test, functions: [{filter(QueryWrapperFi
lter(autocomplete_fr.whitespace:test)), function [boost[10.0]]}]))->cache(BooleanFilter(+cache(visibility:[1 TO 1])))],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"bool":{"must":[{"function_score":{"query":{"bool":{"must":[{"multi_match":{"
query":"test","type":"best_fields","tie_breaker":1,"fields":["autocomplete_fr.edge_ngram_front"],"analyzer":"analyzer_fr","minimum_should_match":"100%"}}]}},"functions":[{"filter"
:{"query":{"query_string":{"query":"test","default_field":"autocomplete_fr.whitespace"}}},"boost_factor":10}]}}]}},"filter":{"bool":{"must":[{"terms":{"visibility":[3,4]}},{"terms
":{"status":[1]}},{"terms":{"in_stock":[1]}},{"terms":{"store_id":[1]}}],"_cache":true}}}},"facets":{"name":{"terms_stats":{"size":"3","order":"total","key_field":"name_fr.untouch
ed","value_script":"_score"}}},"fields":["entity_id"],"track_scores":true,"sort":[{"_score":"desc"}],"from":0,"size":"3"}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:370)
        at org.elasticsearch.search.action.SearchServiceTransportAction$11.call(SearchServiceTransportAction.java:333)
        at org.elasticsearch.search.action.SearchServiceTransportAction$11.call(SearchServiceTransportAction.java:330)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.facet.FacetPhaseExecutionException: Facet [name]: failed to find mapping for name_fr.untouched
        at org.elasticsearch.search.facet.termsstats.TermsStatsFacetParser.parse(TermsStatsFacetParser.java:126)
        at org.elasticsearch.search.facet.FacetParseElement.parse(FacetParseElement.java:93)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
`
-------------------------------------------------------------------------------------`

Did you encounter such an error?

Thank you for your help

**Comment by romainruaud** [comment]
Hello @aitsakel 

It seems that Elastic did not find the proper mapping for the "name" field. Did you reindex after this ? This should be enough to get it working.

Can you give us an update about this ?

Regards,

**Comment by faissal-topo** [comment]
Hi @romainruaud,
The problem persists even after re-indexing.
but when I changed the setting for "name" field as following, I got rid of the problem :

![2016-10-11_23h03_46](https://cloud.githubusercontent.com/assets/22656472/19290355/39fd4298-9007-11e6-8b07-dcdbe4d2a877.png)

I chose the value ""Filtrage (avec résultat)"" or the "Filtrage (sans résultat)" value instead of the "Non"

Regards,

**Comment by romainruaud** [comment]
That's kinda strange.

Can I show the full configuration of the name attribute on your instance ? To be able to reproduce it locally.

Regards,

**Comment by faissal-topo** [comment]
here it is :
![2016-10-12_09h34_21](https://cloud.githubusercontent.com/assets/22656472/19303640/651cb04e-9061-11e6-852c-ec54140b1260.png)
![2016-10-12_09h42_37](https://cloud.githubusercontent.com/assets/22656472/19303643/658806dc-9061-11e6-840f-2c6e9a811c56.png)
![2016-10-12_09h43_04](https://cloud.githubusercontent.com/assets/22656472/19303644/65f2871e-9061-11e6-84ab-3c3950a85294.png)

For your information, I'm using Magento EE 1.14.

Thank you for your help

**Comment by romainruaud** [comment]
Hello,

try to set the "Afficher dans l'autocomplétion" to "Non".

It has no sense to put this to "Oui" for the name, because products are already displayed into the autocomplete (and therefore do their names).

Tell me if this is working,

Regards.

**Comment by romainruaud** [comment]
I close this one for inactivity.

Please feel free to reopen if needed @aitsakel
